### ISSUE TITLE
Class cast exception 

### ISSUE THREAD

**Issue by Moorthy70** [rasmusson/OpenSAML-sample-code#1]
java.lang.ClassCastException: class org.opensaml.saml.saml2.core.impl.ResponseImpl cannot be cast to class org.opensaml.saml.saml2.core.AuthnRequest (org.opensaml.saml.saml2.core.impl.ResponseImpl and org.opensaml.saml.saml2.core.AuthnRequest are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @12aeb4f4)
	at ReceiverServlet.doPost(ReceiverServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Moorthy70** [comment]
I hope you give me a solution

**Comment by gtiwari2015** [comment]
i am also getting this exception what may be the reason

**Comment by davidsielert** [comment]
@Moorthy70  did you find a solution ?

**Comment by irinadiaz** [comment]
Hi @Moorthy70, wondering if you could resolve this issue?. I am having the same error!

**Comment by rasmusson** [comment]
@irinadiaz Last emails on this ended up in a folder I didnt look into. I will look into this. What specific sample are you trying to run?
What JDK version are you on?

**Comment by MrJGentry** [comment]
I'm seeing this same issue, @rasmusson I'm trying to run the OpenSAML Signing and Verification sample project, getting this error from line 59 of the ReceiverServlet.
JDK 1.8.0_172
opensaml version 3.1.1

-e
I ended up getting around this issue by simply not using the AuthnRequest cast. The main use of the AuthnRequest object was the call to getSignature() which is also accessible if you cast to ResponseImpl, I just cast to that instead. The other use was passing the authnRequest into the logSAMLObject method which also works with the a ResponseImpl object.

**Comment by rasmusson** [comment]
Im trying to reproduce it but am not able to. @MrJGentry You say above that you are using 3.1.1. Is that correct? The version used in my code is 4.1.1

**Comment by rasmusson** [comment]
Tried to recreate this from a fresh VM. Using jkd 11 which is needed for opensaml 4. I get no error.
Did you all just checkout and run mvn tomct:run or did you do any changes to the code?
